baseURL = "https://kristof-nyr.github.io/"
locale = "en-US"
title = "Kristof Nyari"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false
  [markup.highlight]
    noClasses = false
    style = "monokailight"

[params]
  description = "software engineer"
  github = "https://github.com/kristof-nyr"
  email = "mailto:kristofnyr@proton.me"
  linkedin = "https://linkedin.com/in/kristof-nyr"

[permalinks]
  writing = "/writing/:slug/"

[outputs]
  home = ["HTML"]
  section = ["HTML"]
